name: easy_localization_loader
description: Easy Localization Loader custom assets loaders for easy_localization (Json, CSV, http, Xml, API ...)
# author: AISSAT abdelwahab <mr.aissat@gmail.com>
homepage: https://github.com/aissat/easy_localization_loader
issue_tracker: https://github.com/aissat/easy_localization_loader/issues

version: 1.0.1+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  http: ^0.13.6
  csv: ^5.0.2
  yaml: ^3.1.2
  xml: ^6.3.0
  flutter:
    sdk: flutter
  connectivity_plus: ^4.0.0
  path_provider: ^2.0.15

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.24.2
